### ISSUE TITLE
Some datasets geographically restricted

### ISSUE THREAD

**Issue by thymaro** [piMoll/swissgeodownloader#5]
Congrats on the plugin. It's great. Getting the list of available datasets works again, that's nice. The following is not to complain or anything like that, I'm just asking to understand and to report bugs or what seems like bugs.

There seem to be missing datasets or timestamps. Take swissalti3d and the region between Cham and Horgen. In the plugin, we can choose between datasets from 2019 and 2021, but not 2020. It seems there are datasets from 2020 that might fill (some of) the holes in the (combination of) the two other datasets. Can you confirm this on your end?

**Comment by piMoll** [comment]
Hi thymaro
Thanks very much for this question. There is indeed something strange going on. 

To fill in the dataset properties in the UI (timestamps, formats, etc,) I request dataset properties from [https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissalti3d](https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissalti3d)
The dataset properties tell me that there are 2 timestamps: 2019 and 2021. But when requesting data for the area between Cham and Horgen I get data for at least 3 timestamps (2019, 2020, 2021). So the properties of the dataset seem to be wrong.

I will inform swisstopo about this, maybe they can fix it. 

Also, I think it would make sense to add an option "all" for timestamps in the next release.  Lots of people just want to download all available data.

**Comment by piMoll** [comment]
A guy at swisstopo has informed me that the temporal extent of the dataset describes an interval, not a list of available timestamps.  

This means that my implementation of the timestamp selection is wrong and you can't get timestamps in between 2019 and 2021. Sorry about that. This issue concerns swissalti3d and in general all datasets that have more than 2 timestamps.

I will fix this in the next release and probably do some reorganization of the UI parts, remove the dataset properties and instead add file filters. I think this makes much more sense and will lead to less problems in the future.

Thanks for spotting this!

**Comment by thymaro** [comment]
sorry, didn't see your latest reply! They already answered, that's great.

Hey, cool, I'm eager to see what you will do with it next. I wish I could help you more on the technical side of things, but my coding abilities aren't up to par, yet.
