### ISSUE TITLE
Feature request: swissgeodownloader for R

### ISSUE THREAD

**Issue by martinzbinden** [piMoll/swissgeodownloader#9]
I would highly appreciate if swissgeodownloader would also be available as a R library.

**Comment by piMoll** [comment]
Sorry for this ridiculously late answer!

This plugin heavily depends on QGIS and Qt functionality. To use it within R, I think the plugin would have to be rewritten. 
I sadly don't have any experience with R, so this would be a very big tasks. 
But  if you want to try it yourself, go for it ;)
